# Generated by Django 3.1.3 on 2020-11-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, verbose_name='Apellido')),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=12, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_work_sq', models.IntegerField()),
                ('ISWC', models.CharField(blank=True, max_length=10, verbose_name='ISWC')),
                ('titulo', models.CharField(blank=True, max_length=250, verbose_name='Titulo')),
                ('autor', models.CharField(blank=True, max_length=250, verbose_name='Autor')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagweb.persona')),
            ],
        ),
    ]
